<?php

return [
    [
        'name' => 'Wood',
        'slug' => 'wood',
        'description' => 'A basic construction material, widely available.',
        'unit' => 'unit',
        'base_price' => 10,
    ],
    [
        'name' => 'Iron Ore',
        'slug' => 'iron-ore',
        'description' => 'Raw material for metal production.',
        'unit' => 'unit',
        'base_price' => 15,
    ],
    [
        'name' => 'Coal',
        'slug' => 'coal',
        'description' => 'Essential fuel for locomotives and industrial processes.',
        'unit' => 'unit',
        'is_fuel' => '1',
        'fuel_value' => '1',
        'base_price' => 15,
    ],
    [
        'name' => 'Grain',
        'slug' => 'grain',
        'description' => 'Staple food, can be processed into other goods.',
        'unit' => 'unit',
        'base_price' => 5,
    ],
    [
        'name' => 'Copper Ore',
        'slug' => 'copper-ore',
        'description' => 'Raw material for electrical and mechanical components.',
        'unit' => 'unit',
        'base_price' => 20,
    ],
    [
        'name' => 'Stone',
        'slug' => 'stone',
        'description' => 'Durable building material, used in infrastructure.',
        'unit' => 'unit',
        'base_price' => 12,
    ],
    [
        'name' => 'Crude Oil',
        'slug' => 'crude-oil',
        'description' => 'Unrefined petroleum, source of energy and lubricants.',
        'unit' => 'unit',
        'is_fuel' => '1',
        'fuel_value' => '2',
        'base_price' => 25,
    ],
    [
        'name' => 'Clay',
        'slug' => 'clay',
        'description' => 'Malleable earth material, used in ceramics and bricks.',
        'unit' => 'unit',
        'base_price' => 8,
    ],
    [
        'name' => 'Sand',
        'slug' => 'sand',
        'description' => 'Granular material, essential for glass and concrete.',
        'unit' => 'unit',
        'base_price' => 7,
    ],
];
